.model small		;DECLARACION DEL MODELO
.data				;SEGMENTO DE DATOS
	textoInicial DB 'Ingrese un numero $'
	num1 DB ?
	num2 DB ?
	residuo DB ?
.stack
.code

Programa:

	;	INICIO PROGRAMA
	MOV AX, @DATA	;INICIO
	MOV DS, AX		;INICIALIZA SEGMENTO DE DATOS
	
	;	IMPRIMIR INSTRUCCIONES AL USUARIO
	MOV DX, OFFSET textoInicial
	MOV AH, 09H
	INT 21H
	
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	
	;	LEER NUMERO
	MOV AH, 01H		;INTERRUMPCION PARA LEER
	INT 21H
	
	SUB AL, 30H		;CONVERTIR A NUMERO REAL
	MOV num1, AL	;ASIGNAR A num1
	
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	
	;	LEER SEGUNDO NUMERO
	MOV AH, 01H		;INTERRUMPCION PARA LEER
	INT 21H
	
	SUB AL, 30H		;CONVERTIR A NUMERO REAL
	MOV num2, AL	;ASIGNAR A num1

	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	
	;	MULTIPLICACION
	XOR AX, AX		;LIMPIAR AX
	MOV AL, num1	;OPERANDO 1
	MOV BL, num2	;OPERANDO 2
	MUL BL			;MULTIPLICACION AL * BL
	
	;	IMPRIMIR EN PANTALLA
	MOV DX, AX
	ADD DX, 30H
	MOV AH, 02H
	INT 21H
	
	;	DIVISION
	XOR AX, AX
	MOV AL, num1	;DIVIDENDO
	MOV BL, num2	;DIVISOR
	DIV BL			;DIVISION AX / BL
	MOV residuo, AH ;GUARDAR RESIDUO
	
	;	IMPRIMIR EN PANTALLA
	;COCIENTE
	MOV DL, AL
	ADD DL, 30H
	MOV AH, 02H
	INT 21H
	;RESIDUO
	MOV DL, residuo
	ADD DL, 30H
	INT 21H
	
	;	IMPRIMIR EN PANTALLA
	;MOV DL, num1	;IMPRIMIR VARIABLE
	;ADD DL, 30H		;CONVERTIR A ASCII
	;INT 21H
	
	;	FINALIZACION DEL PROGRAMA
	MOV AH, 4Ch
	INT 21h

End Programa