.model small		;DECLARACION DEL MODELO
.data				;SEGMENTO DE DATOS
	bienvenida DB 'Bienvenido al sistema de alertas COVID-19 $'
	instruccion1 DB 'Ingrese cantidad de pruebas: $'
	instruccion2 DB 'Ingrese cantidad de casos positivos: $'
	resultado DB 'Alerta: $'
	rojo DB 'Alerta roja$'
	naranja DB 'Alerta naranja$'
	amarillo DB 'Alerta amarilla$'
	verde DB 'Alerta verde$'
	_error DB 'Error. Las pruebas positivas no pueden ser mayores a las pruebas totales.$'
	_errorNum DB 'Error. Se esperaba un numero.$'
	num1 DB ?
	num2 DB ?
	num3 DB ?
	pruebas DW ?
	positivos DW ?
	porcentaje DW ?
.stack
.code

Programa:

	;	INICIO PROGRAMA
	MOV AX, @DATA	;INICIO
	MOV DS, AX		;INICIALIZA SEGMENTO DE DATOS

INICIO:
	
	;	INSTRUCCIONES Y LECTURA DE INPUT
	;SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	;MENSAJE DE BIENVENIDA
	MOV DX, OFFSET bienvenida
	MOV AH, 09H		;INTERRUPCION DE IMPRESION DE CADENA
	INT 21H
	;SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	
L_PRUEBAS:

	;SOLICITAR INGRESO DE PRUEBAS REALIZADAS
	MOV DX, OFFSET instruccion1
	MOV AH, 09H		;INTERRUPCION DE IMPRESION DE CADENA
	INT 21H
	;REALIZAR SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	;	LEER NUMERO
	MOV DH, 0H		;INDICAR QUE ESTAMOS EN LA PRIMERA INSTRUCCION
	JMP LEER
	
L_POSITIVOS:

	;REALIZAR SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	;SOLICITAR INGRESO DE PRUEBAS REALIZADAS
	MOV DX, OFFSET instruccion2
	MOV AH, 09H		;INTERRUPCION DE IMPRESION DE CADENA
	INT 21H
	;REALIZAR SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	;	LEER NUMERO
	MOV DH, 1H		;INDICAR QUE ESTAMOS EN LA SEGUNDA INSTRUCCION
	JMP LEER
	
L_ALERTAS:
	
	;REALIZAR SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	;VALIDAR ENTRADA
	MOV DX, pruebas
	CMP DX, positivos
	JL  MSG_ERROR
	;LIMPIAR REGISTROS
	XOR AX, AX
	XOR BX, BX
	XOR CX, CX
	;CALCULO DE PORCENTAJE
	MOV AX, positivos	;DIVIDENDO
	MOV BX, pruebas		;DIVISOR
	MOV CX, 100D
	MUL CX				;AX * 100 (PORCENTAJE)
	DIV BX				;DIVISION AX / BX
	MOV porcentaje, AX  ;GUARDAR RESULTADO
	
	;IMPRIMIR RESULTADO
	MOV DX, OFFSET resultado
	MOV AH, 09H		
	INT 21H
	
	MOV DX, porcentaje	
	CMP DX, 20D			;COMPARAR % > 20
	JGE MSG_ROJO
	CMP DX, 15D			;COMPARAR % > 15
	JGE MSG_NARANJA
	CMP DX, 5D			;COMPARAR % > 5
	JGE MSG_AMARILLO
	JMP MSG_VERDE		;ELSE
	
	MSG_VERDE:
	MOV DX, OFFSET verde
	MOV AH, 09H		
	INT 21H
	JMP FIN
	MSG_AMARILLO:
	MOV DX, OFFSET amarillo
	MOV AH, 09H		
	INT 21H
	JMP FIN
	MSG_NARANJA:
	MOV DX, OFFSET naranja
	MOV AH, 09H		
	INT 21H
	JMP FIN
	MSG_ROJO:
	MOV DX, OFFSET rojo
	MOV AH, 09H		
	INT 21H
	JMP FIN
	MSG_ERROR:
	MOV DX, OFFSET _error
	MOV AH, 09H		
	INT 21H
	JMP FIN
	
	
FIN:
	;REALIZAR SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	;	FINALIZACION DEL PROGRAMA
	MOV AH, 4Ch
	INT 21h


;		FUNCIONES	
LEER:

	;LECTURA DE DIGITOS
	;PRIMER DIGITO
	MOV AH, 01H		;INTERRUMPCION PARA LEER
	INT 21H
	SUB AL, 30H		;CONVERTIR A NUMERO REAL
	MOV num1, AL	;ASIGNAR PRIMER DIGITO A num1
	
	;SEGUNDO DIGITO
	INT 21H
	SUB AL, 30H		;CONVERTIR A NUMERO REAL
	MOV num2, AL	;ASIGNAR SEGUNDO DIGITO A num2
	;TERCER DIGITO
	INT 21H
	SUB AL, 30H		;CONVERTIR A NUMERO REAL
	MOV num3, AL	;ASIGNAR TERCER DIGITO A num3
	
	;VALIDAR ENTRADA
	JMP VALIDAR_NUMERO
	
	_VALOR:
	;CALCULAR VALOR
	;LIMPIAR REGISTRO
	XOR AX, AX
	XOR BX, BX
	XOR CX, CX
	
	;CALCULAR CENTENAS
	MOV AL, num1	;DIGITO 1
	MOV CL, 100D
	MUL CL			;AX * 100
	ADD BX, AX		;SUMAR RESULTADO
	;CALCULAR DECENAS
	MOV AL, num2	;DIGITO 2
	MOV CL, 0AH
	MUL CL			;AL * 10
	ADD BX, AX		;SUMAR RESULTADO
	;CALCULAR DECENAS
	MOV AL, num3	;DIGITO 3
	ADD BX, AX		;SUMAR VALOR
	
	;SALTO A ASIGNACION DEL VALOR
	CMP DH, 0H		;COMPARAR BANDERA DE POSICION
	JE ASIG_PRUEBA
	JMP ASIG_POSITIVO
	
ASIG_PRUEBA:
	
	MOV pruebas, BX
	JMP L_POSITIVOS

ASIG_POSITIVO:

	MOV positivos, BX
	JMP L_ALERTAS

VALIDAR_NUMERO:
	
	MOV DL, num1
	CMP DL, 9H		;VALIDAR SI ES MAYOR AL 9
	JG ERROR_NUMERO
	CMP DL, 0H		;VALIDAR SI ES MENOR AL 0
	JL ERROR_NUMERO
	
	MOV DL, num2
	CMP DL, 9H		;VALIDAR SI ES MAYOR AL 9
	JG ERROR_NUMERO
	CMP DL, 0H		;VALIDAR SI ES MENOR AL 0
	JL ERROR_NUMERO

	MOV DL, num3
	CMP DL, 9H		;VALIDAR SI ES MAYOR AL 9
	JG ERROR_NUMERO
	CMP DL, 0H		;VALIDAR SI ES MENOR AL 0
	JL ERROR_NUMERO
	
	JMP _VALOR		;ES CORRECTO, REGRESAR
	
ERROR_NUMERO:

	;REALIZAR SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	;MENSAJE DE ERROR
	MOV DX, OFFSET _errorNum
	MOV AH, 09H		;INTERRUPCION DE IMPRESION DE CADENA
	INT 21H
	;REALIZAR SALTO DE LINEA
	MOV DL, 0AH		;SALTO DE LINEA
	MOV AH, 02H		;IMPRIMIR CARACTER
	INT 21H
	
	JMP INICIO		;REGRESAR A INICIO
	
End Programa